version: '3.8'

services:
  app:
    image: openjdk:21
    container_name: java-app
    ports:
      - 8888:8080
    tty: true
    volumes:
      - ./demo:/srv:cached
    working_dir: /srv
    depends_on:
      - db

  adminer:
    image: adminer:4.7.8
    container_name: java-adminer
    ports:
      - "9000:8080"
    depends_on:
      - db

  db:
    image: postgres:13.1
    container_name: java-db
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "dev"
    ports:
      - "5433:5432"
    volumes:
      - dbvol:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d

volumes:
  dbvol: